<a href="https://colab.research.google.com/github/tirtharajghosh/Machine-Learning/blob/master/Data_Preprocessing_Template.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Importing required libraries

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

### Importing dataset

In [ ]:
dataset = pd.read_csv('/content/drive/My Drive/Colab Notebooks/Datasets/Data.csv')
x = dataset.iloc[:,:-1].values
y = dataset.iloc[:,3].values

#print("Value of X :\n",x)
#print("Value of Y :\n",y)

### Taking care of missing data
  Note: `Imputer` class is deprecated. Instead used `SimpleImputer`. It only imputes along columns data i.e no axis parameter.

In [ ]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values = np.nan, strategy = 'mean', verbose = 0)
imputer = imputer.fit(x[:,1:3])
x[:,1:3] = imputer.transform(x[:,1:3])

### Encoding categorical data - Dummy Variables
  Note: We don't always need to use `LabelEncoder` anymore. Instead used `ColumnTransfer`.

In [ ]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer([("Country", OneHotEncoder(), [0])], remainder = 'passthrough')
x = ct.fit_transform(x)
labelencoder_y = LabelEncoder()
y = labelencoder_y.fit_transform(y)

#print("Value of X after Dummy Variable Encoding:\n",x)
#print("Value of Y after Dummy Variable Encoding:\n",y)

### Splitting dataset - Training and Test
  Note: `cross_validation` name is now deprecated and was replaced by `model_selection`



In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state = 0)

### Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc_x = StandardScaler();
x_train = sc_x.fit_transform(x_train)
x_test =  sc_x.transform(x_test)

print(x_train)
print(x_test)

[[-1.          2.64575131 -0.77459667  0.26306757  0.12381479]
 [ 1.         -0.37796447 -0.77459667 -0.25350148  0.46175632]
 [-1.         -0.37796447  1.29099445 -1.97539832 -1.53093341]
 [-1.         -0.37796447  1.29099445  0.05261351 -1.11141978]
 [ 1.         -0.37796447 -0.77459667  1.64058505  1.7202972 ]
 [-1.         -0.37796447  1.29099445 -0.0813118  -0.16751412]
 [ 1.         -0.37796447 -0.77459667  0.95182631  0.98614835]
 [ 1.         -0.37796447 -0.77459667 -0.59788085 -0.48214934]]
[[-1.          2.64575131 -0.77459667 -1.45882927 -0.90166297]
 [-1.          2.64575131 -0.77459667  1.98496442  2.13981082]]
